spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 568311594235815
            clientSecret: 453d8855e3282a991bc19a0cc9950cec
          github:
            clientId: 79a8365997638281ca47
            clientSecret: 043956a4e77c629753446199c4dcc2b734073899
          google:
            clientId: 427409049331-f0r93km2p4djvn69kofdh7n8i7gquch0.apps.googleusercontent.com
            clientSecret: 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
